# Coloque este arquivo em: .github/workflows/metrics.yml
name: Metrics

on:
  schedule: [{cron: "0 * * * *"}]   # Atualiza a cada hora
  workflow_dispatch:                 # Permite rodar manualmente
  push: {branches: ["main", "master"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg

          # Base (perfil, repositórios, stars, etc)
          base: header, activity, community, repositories

          config_timezone: America/Manaus
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_threshold: 0%

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 7
          plugin_habits_facts: no

          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: no

          plugin_stars: yes
          plugin_stars_limit: 4

          plugin_topics: yes
          plugin_topics_limit: 8
